variables:
- name: ml-ws-connection
  value: aml-workspace-connection-3
- name: ml-ws
  value: jenns-centralus
- name: ml-rg
  value: jenns
- name: ml-ct
  value: cpu-cluster-1
- name: ml-path
  value: models/diabetes
- name: ml-exp
  value: exp-test
- name: ml-model-name
  value: diabetes-model
- name: ml-aks-name
  value: aks-prod
trigger:
  branches:
    include:
    - '*'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: Ubuntu-16.04
    steps:
    - task: AzureCLI@2
      displayName: Install AML CLI
      inputs:
        azureSubscription: $(ml-ws-connection)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: az extension add -n azure-cli-ml
    - task: AzureCLI@2
      displayName: Attach folder to workspace
      inputs:
        azureSubscription: $(ml-ws-connection)
        workingDirectory: $(ml-path)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: az ml folder attach -w $(ml-ws) -g $(ml-rg)
    - task: AzureCLI@2
      displayName: Train model
      inputs:
        azureSubscription: $(ml-ws-connection)
        workingDirectory: $(ml-path)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: az ml run submit-script -c config/train --ct $(ml-ct) -e $(ml-exp) -t run.json train.py
    - task: AzureCLI@2
      displayName: Register model
      inputs:
        azureSubscription: $(ml-ws-connection)
        workingDirectory: $(ml-path)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: az ml model register -n $(ml-model-name) -f run.json --asset-path outputs/ridge_0.95.pkl -t model.json
    - task: AzureCLI@2
      displayName: Deploy model to ACI for QA
      inputs:
        azureSubscription: $(ml-ws-connection)
        workingDirectory: $(ml-path)
        scriptLocation: inlineScript
        scriptType: bash
        inlineScript: az ml model deploy -n diabetes-qa-aci -f model.json --ic config/inference-config.yml --dc config/deployment-config-aci.yml --overwrite

